### ISSUE TITLE
ITS NOT WORKING

### ISSUE THREAD

**Issue by taygunsavas** [Benio101/Aye.Doomsayer#1]
Issue is so simple,It's not working at all. 
I cant use /aye doomsayer command while in raid.

P.S. : I'am the leader of the raid.I understand it cant work if you're just a member of it. Either way its not working.

**Comment by Benio101** [comment]
Cannot reproduce (no reproduction steps given at all).
Make sure to have both Aye.Doomsayer and it's Depot: Aye enabled.
This should result in short description of Aye.Doomsayer in Interface → Addons → Aye → Aye.Doomsayer settings.
`/aye doomsayer` command will also not output anything if there are not issues.
PS You don't need to be neither raid leader, nor even in raid to use this command.
